version: 2
jobs:
    build:
        working_directory: /go/src/github.com/ieee0824/circleci-test
        docker:
            - image: docker:1.13.1-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install Packages
                command: |
                    apk add --no-cache -t .deps ca-certificates curl && \
                    GLIBC_VERSION='2.23-r3' && \
                    curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && \
                    curl -Lo glibc.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-$GLIBC_VERSION.apk && \
                    curl -Lo glibc-bin.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-bin-$GLIBC_VERSION.apk && \
                    apk update && \
                    apk add glibc.apk glibc-bin.apk && \
                    rm -rf /var/cache/apk/* && \
                    rm glibc.apk glibc-bin.apk && \
                    apk del .deps
            - run:
                name: Install Docker Compose
                command: |
                    set -e
                    curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                    chmod +x /usr/local/bin/docker-compose
            - run:
                name: Check Docker Compose
                command: |
                    which docker-compose
                    echo $PATH

